Movie.destroy_all
User.destroy_all
Review.destroy_all
Movie.reset_pk_sequence
User.reset_pk_sequence
Review.reset_pk_sequence 

# m1 = Movie.create(title: "Scooby Doo", description: "a classic tale of a dog and their human", genre: "comedy")
# m2 = Movie.create(title: "Dracula", description: "a tragic tale of darkness", genre: "horror") 
# m3 = Movie.create(title: "Home Alone", description: "a courageous tale of family", genre: "comedy")  
# m4 = Movie.create(title: "Memento", description: "a crazy tale of no memories", genre: "thriller")  
# m5 = Movie.create(title: "Hocus Pocus", description: "a tale of eating children and witches", genre: "comedy")   
# m6 = Movie.create(title: "Die Hard", description: "a tale of bravery and glass in feet", genre: "action")  

m1 = Movie.create(title: "The Wizard Of Oz", description: "a tale of tornados and no place like home (1939)", genre: "fantasy")
m2 = Movie.create(title: "Citizen Kane", description: "a tale of a publishing tycoon's rise and fall (1941)", genre: "drama")  
m3 = Movie.create(title: "The Cabinet Of Dr. Caligari", description: "a tale of hypnonsis and carnivals (1920)", genre: "horror") 
m4 = Movie.create(title: "Modern Times", description: "a tale of monotony and evil machines (1936)", genre: "comedy") 
m5 = Movie.create(title: "The Third Man", description: "a tale of Vienna and the black market (1949)", genre: "thriller") 
m6 = Movie.create(title: "Casablanca", description: "a tale of wartime romance and rebels (1942)", genre: "drama") 
m7 = Movie.create(title: "It Happened One Night", description: "a tale of a spolied heiress on a bus (1934)", genre: "comedy") 
m8 = Movie.create(title: "La Grande Illusion", description: "a tale of war, POWs, and strange hospitality (1938)", genre: "drama") 
m9 = Movie.create(title: "All About Eve", description: "a tale of Broadway, and pitiful manipulation (1950)", genre: "drama") 
m10 = Movie.create(title: "Snow White And The Seven Dwarfs", description: "a tale of lots and lots of dwarfs (1937)", genre: "animation") 
m11 = Movie.create(title: "The Bride Of Frankenstein", description: "a tale of monsters and true love (1935)", genre: "horror") 
m12 = Movie.create(title: "Singin' In The Rain", description: "a tale of true jealousy and rain (1952)", genre: "comedy") 
m13 = Movie.create(title: "King Kong", description: "a tale of bravery, betrayal, and bananas (1933)", genre: "action") 
m14 = Movie.create(title: "The Adventures Of Robin Hood", description: "a tale of thievery and pure adventure (1938)", genre: "action") 
m15 = Movie.create(title: "Metropolis", description: "a tale of a futuristic city and a prophet (1927)", genre: "drama") 
m16 = Movie.create(title: "Laura", description: "a tale of obsession and downright murder (1944)", genre: "mystery") 
m17 = Movie.create(title: "A Hard Day's Night", description: "a tale of music and changing the world (1964)", genre: "comedy") 
m18 = Movie.create(title: "The Philadelphia Story", description: "a tale of marriage, alcohol, and betrayal (1940)", genre: "comedy") 
m19 = Movie.create(title: "Nosferatu", description: "a tale of vampires and a scary castle (1922)", genre: "horror")  
m20 = Movie.create(title: "Psycho", description: "a tale of paranoia and a mysterious mother (1960)", genre: "horror") 

u1 = User.create(username: "Jmknopf1007", age: 47) 
u2 = User.create(username: "Tanner3", age: 76)  
u3 = User.create(username: "Tiannsimmons", age: 28)    
u4 = User.create(username: "Michaelz", age: 16)    
u5 = User.create(username: "Helen3456", age: 65)    
u6 = User.create(username: "Seansean2", age: 55)     

r1 = Review.create(movie_id: m1.id, user_id: u1.id, rating:  8) 
r2 = Review.create(movie_id: m2.id, user_id: u1.id, rating:  1) 
r3 = Review.create(movie_id: m2.id, user_id: u2.id, rating:  9)  
r4 = Review.create(movie_id: m3.id, user_id: u3.id, rating:  9)      
r5 = Review.create(movie_id: m1.id, user_id: u3.id, rating:  8)        
r6 = Review.create(movie_id: m4.id, user_id: u4.id, rating:  7)         
r7 = Review.create(movie_id: m5.id, user_id: u4.id, rating:  8)         
r8 = Review.create(movie_id: m5.id, user_id: u1.id, rating:  9)          
r9 = Review.create(movie_id: m5.id, user_id: u5.id, rating:  6)         
r10 = Review.create(movie_id: m1.id, user_id: u6.id, rating:  7)         
r11 = Review.create(movie_id: m4.id, user_id: u6.id, rating:  8)          
r12 = Review.create(movie_id: m6.id, user_id: u2.id, rating:  6)         
r13 = Review.create(movie_id: m4.id, user_id: u2.id, rating:  4)         
r14 = Review.create(movie_id: m5.id, user_id: u3.id, rating:  9)         
r15 = Review.create(movie_id: m4.id, user_id: u3.id, rating:  6)          